/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Async Node.js wrapper around the core `execute_test` function */
export declare function executeTestAsync(testArtifactPath: string, testName: string, perfReportConfig?: PerfReportConfig | undefined | null): Promise<TestResult>

/** Synchronous Node.js wrapper around the core `execute_test` function */
export declare function executeTestSync(testArtifactPath: string, testName: string, perfReportConfig?: PerfReportConfig | undefined | null): TestResult

export interface PerfReport {
  instructions?: number
  instructionsPerCycle?: number
  lastLevelCacheHitRate?: number
  l1DataCacheHitRate?: number
  l1InstructionCacheMisses?: number
  branchMissRatio?: number
  cpuMigrations?: number
}

export interface PerfReportConfig {
  instructions: boolean
  instructionsPerCycle: boolean
  lastLevelCacheHitRate: boolean
  l1DataCacheHitRate: boolean
  l1InstructionCacheMisses: boolean
  branchMissRatio: boolean
  cpuMigrations: boolean
}

export interface TestResult {
  /** Execution time of the REVM transaction */
  durationNs: number
  perfReport?: PerfReport
}
