/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Async Node.js wrapper around the core `execute_test` function */
export declare function executeTestAsync(testArtifactPath: string, testName: string, collectCacheHitRatio: boolean): Promise<TestResult>

/** Synchronous Node.js wrapper around the core `execute_test` function */
export declare function executeTestSync(testArtifactPath: string, testName: string, collectCacheHitRatio: boolean): TestResult

export interface TestResult {
  /** Execution time of the REVM transaction */
  durationNs: number
  /** CPU cache hit ratio of the REVM transaction */
  cacheHitRatio?: number
}
