/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Node.js wrapper around the core `execute_test` function */
export declare function executeTest(testArtifactPath: string, testName: string): bigint
